flex:
  version: 0.5.6
  workflows:
    build:
      command: scripts/build.sh
    deploy:
      command: >
        docker run
        -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        -e ENV=${ENV:-dev}
        -e TAG=${TAG:-1.0.0-SNAPSHOT}
        -v $PWD:/workdir
        jshimko/kube-tools-aws:3.7.0
        bash -c "cd /workdir && ./scripts/deploy.sh"
    publish:
      command: service_name=devx-helloworld-springboot-wov3t scripts/publish.sh
service:
  name: devx-helloworld-springboot-wov3t
