apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: devx-helloworld-springboot-wov3t
    backstage.io/kubernetes-id: devx-helloworld-springboot-wov3t
  name: devx-helloworld-springboot-wov3t
  namespace: '{{ .Values.config.namespace }}'
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: devx-helloworld-springboot-wov3t
